hide_download: true
hide_download_original: null
leftnav:
- identifier: 3a5e16b0-b7ea-9dcc-a7aa-7d11b20e9394
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 7be777ed-2b62-8611-d045-22e0c9feab52
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: aafe6703-d47b-813a-9b35-2f688a2ca986
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 30
- identifier: d526b275-1005-cc6f-c022-f7e724fc44b5
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: cc4b3de6-7021-0f46-cab8-9eca8bf0554d
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 50
- identifier: 204c5d62-df99-e26a-614d-c66e5cfbe449
  name: Assignments
  pageRef: /pages/assignments
  weight: 60
- identifier: 7e3bc46b-f99c-8496-994d-4c3a17426de4
  name: Exams
  pageRef: /pages/exams
  weight: 70
- identifier: 3df7454b-e0cf-9033-4986-6d61a926efe4
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 80
